"use client";

import { useOptimistic, useTransition } from "react";
import { Users, Mail, Calendar, Briefcase, DollarSign } from "lucide-react";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { DeleteLeadButton } from "@/components/admin/delete-lead-button";
import { EmptyState } from "@/components/admin/empty-state";
import type { Lead } from "@/lib/types";

export function LeadList({ initialLeads }: { initialLeads: Lead[] }) {
  const [optimisticLeads, removeOptimisticLead] = useOptimistic(
    initialLeads,
    (state, id: string) => state.filter((l) => l.id !== id)
  );
  const [isPending, startTransition] = useTransition();

  const handleDelete = (id: string) => {
    startTransition(() => {
      removeOptimisticLead(id);
    });
  };

  if (optimisticLeads.length === 0) {
    return (
      <EmptyState
        icon={Users}
        title="No leads yet"
        description="When users fill out your contact form, they will appear here as potential opportunities."
        // Leads don't have a "New" page usually as they are generated by users, but we can link to the contact page
        actionLabel="View Contact Page"
        actionHref="/contact"
      />
    );
  }

  return (
    <div className="grid gap-6">
      {optimisticLeads.map((lead: Lead) => (
        <Card key={lead.id} className="hover:border-primary/50 transition-colors group">
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <div className="flex items-center gap-3">
              <div className="h-10 w-10 rounded-full bg-blue-100 flex items-center justify-center text-blue-700 font-bold">
                {lead.name.charAt(0)}
              </div>
              <div>
                <CardTitle className="text-xl font-bold">{lead.name}</CardTitle>
                <div className="flex items-center gap-2 text-xs text-muted-foreground">
                  <Mail className="h-3 w-3" />
                  <span>{lead.email}</span>
                </div>
              </div>
            </div>
            <div className="flex items-center gap-2">
              <span className="text-[10px] uppercase font-bold text-muted-foreground bg-muted px-2 py-1 rounded">
                {lead.created_at ? new Date(lead.created_at).toLocaleDateString() : ""}
              </span>
              <DeleteLeadButton id={lead.id!} name={lead.name} onDelete={handleDelete} />
            </div>
          </CardHeader>
          <CardContent>
            <div className="grid md:grid-cols-3 gap-6 mt-4 border-t pt-4">
              <div className="space-y-1">
                <p className="text-[10px] font-bold text-muted-foreground uppercase tracking-wider flex items-center gap-1">
                  <Briefcase className="h-3 w-3" /> Company
                </p>
                <p className="text-sm font-medium">{lead.company || "Individual"}</p>
              </div>
              <div className="space-y-1">
                <p className="text-[10px] font-bold text-muted-foreground uppercase tracking-wider flex items-center gap-1">
                  <Calendar className="h-3 w-3" /> Requested Meeting
                </p>
                <p className="text-sm font-medium">
                  {lead.requested_date ? new Date(lead.requested_date).toLocaleString() : "No time requested"}
                </p>
              </div>
              <div className="space-y-1">
                <p className="text-[10px] font-bold text-muted-foreground uppercase tracking-wider flex items-center gap-1">
                  <DollarSign className="h-3 w-3" /> Budget Range
                </p>
                <p className={`text-sm font-bold ${lead.budget ? "text-green-600" : "text-muted-foreground"}`}>
                  {lead.budget || "Not specified"}
                </p>
              </div>
            </div>
            <div className="mt-6 pt-4 border-t border-dashed">
              <p className="text-[10px] font-bold text-muted-foreground uppercase tracking-wider mb-2">Message</p>
              <div className="text-sm leading-relaxed whitespace-pre-wrap bg-muted/30 p-4 rounded-md italic border-l-2 border-primary/10">
                "{lead.message}"
              </div>
            </div>
          </CardContent>
        </Card>
      ))}
    </div>
  );
}
